from datetime import datetime
import pandas as pd

class TeslaReportGenerator:
    def __init__(self):
        pass

    def generate_report(self, df_results):
        """
        Generates a markdown report for Tesla-like stocks.
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # 1. Title & Header
        report = f"# 🚀 KOSPI Tesla-like Stock Report\n"
        report += f"**Date**: {now}\n\n"
        
        # 2. Executive Summary
        if df_results.empty:
            report += "## Summary\n"
            report += "No candidates found satisfying the criteria (Liquidity > 100억).\n"
            return report
            
        top_count = len(df_results)
        report += "## 1. Summary\n"
        report += f"- **Total Candidates Found**: {top_count}\n"
        
        # Benchmark Info
        tesla_row = df_results[df_results['ticker'] == 'TSLA']
        if not tesla_row.empty:
            rank = tesla_row.iloc[0]['rank_tvs']
            tvs = tesla_row.iloc[0]['TVS']
            report += f"- **Benchmark (TSLA)**: Rank **#{rank}** (Score: {tvs:.1f})\n"
            if rank == 1:
                report += "  - *Comment*: Tesla is currently the volatility king. KOSPI is relatively quiet.\n"
            elif rank <= 10:
                report += "  - *Comment*: Tesla is in the Top Tier. KOSPI has few contenders.\n"
            else:
                report += "  - *Comment*: There are many KOSPI stocks wilder than Tesla right now!\n"
        report += "\n"

        # 3. Top Candidates
        report += "## 2. Top Candidates (Ranked by TVS)\n"
        report += "Criteria: Hard Filter (Avg Amt > 100억) -> Scoring (Daily Vol 40% + RSI Vol 30% + Weekly Vol 30%)\n\n"
        
        report += "| Rank | Ticker | Name | TVS | Daily Vol | RSI Std | Weekly Vol | Avg Amt (억) |\n"
        report += "|---|---|---|---|---|---|---|---|\n"
        
        # Display Top 20
        top_20 = df_results.head(20)
        for idx, row in top_20.iterrows():
            ticker = row['ticker']
            name = row['name']
            tvs = row['TVS']
            daily = row['daily_vol']
            rsi = row['rsi_std']
            weekly = row['weekly_vol']
            
            # Formatting
            rank = row['rank_tvs'] # Computed in screener logic, or use index + 1
            if 'rank_tvs' not in row:
                rank = idx + 1
                
            amt = row['avg_amount'] / 100_000_000 # 억 단위
            
            # Highlight Tesla
            if ticker == 'TSLA':
                name = f"**{name}**"
            
            report += f"| {rank} | {ticker} | {name} | **{tvs:.1f}** | {daily:.4f} | {rsi:.2f} | {weekly:.4f} | {amt:.0f} |\n"
            
        report += "\n"
        report += "---\n"
        report += "*Generated by Stock Research Bot*\n"
        
        return report
